### ISSUE TITLE
Detect links to SVGs in HTML

### ISSUE THREAD

**Issue by ShimShamSam** [Epimodev/parcel-plugin-svg-sprite#1]
First off, excellent work. You saved me the trouble of having to make my own plugin!
What would be even better is the ability to detect links to SVGs directly from HTML. Such as: 
```
<svg><use href="foo.svg"></svg>
```
Instead of
```
import foo_link from 'foo.svg';

<svg><use href="{{foo_link}}"></svg>
```

Parcel already supports similar behavior for SVGs but doesn't incorporate them into a sprite sheet. Maybe there's a way to overwrite it?

**Comment by Epimodev** [comment]
Hi @ShimShamSam 👋

Thanks a lot for your message. I'm sorry to answer only now (I forgot to enable notification on this project). I'll be more reactive next time 😀.

About your suggestion, it's a good idea 👍.
I'll try to add import from html during this week.

**Comment by Epimodev** [comment]
Hello @ShimShamSam 

I've just create this PR https://github.com/Epimodev/parcel-plugin-svg-sprite/pull/2 where I added the possibility to import svg from html and inject it in sprite.

I publish it on npm with `beta` tag. You can install it by doing the following command :
```sh
yarn add -D parcel-plugin-svg-sprite@beta
# or with npm
npm install -D parcel-plugin-svg-sprite@beta
```

Can you test it and give me feedback in PR please ?

**Comment by Epimodev** [comment]
I finally merge the pull request and publish on npm the version `1.1.1` which handle svg imported from html file. I hope this suits your needs.
