### ISSUE TITLE
`ignore` property

### ISSUE THREAD

**Issue by nikoloza** [Epimodev/parcel-plugin-svg-sprite#23]
Hello,

At some files for example `favicon.svg` we'll need to skip spriting.

some `ignore` pattern would be useful.

**Comment by Epimodev** [comment]
Hi @nikoloza 

There is already an `exclude` option you can find here: https://github.com/Epimodev/parcel-plugin-svg-sprite#options-

In your case, you can add in your `package.json` the following lines:
```json
// package.json
"name": "my-package-name",
...
"svgSpriteOptions": {
  "exclude": ["**/favicon.svg"]
}
```
