### ISSUE TITLE
Split sprites to each page

### ISSUE THREAD

**Issue by dx1ded** [Epimodev/parcel-plugin-svg-sprite#28]
My case: i have a multipage project (there's 9 html-pages) and i want to use certain sprites in each page. In real situation, there's all sprites rendered in each page. How to do that? Thanks.

**Comment by Epimodev** [comment]
Hi @dx1ded unfortunately this is a limitation of this plugin and I didn't found a solution.  
For your use case, maybe build each html page with a separate command could work.  
For example:
```sh
parcel src/page1.html
parcel src/page2.html
parcel src/page3.html
parcel src/page4.html
```

**Comment by dx1ded** [comment]
@Epimodev yeah, u're truth, but it's too inconvenient
