### ISSUE TITLE
Issues with xxhash on node 12

### ISSUE THREAD

**Issue by wroughtec** [Epimodev/parcel-plugin-svg-sprite#3]
Have opened an issue on the xxhash:
https://github.com/mscdex/node-xxhash/issues/31

**Comment by Epimodev** [comment]
Hi @wroughtec 

thanks for this information, maybe I can replace `xxhash` by `xxhashjs` to avoid this error.
I'll try to make this change later today.

**Comment by wroughtec** [comment]
Sounds like a plan 👍

**Comment by Epimodev** [comment]
I've just try to replace `xxhash` by `xxhashjs` and I've got the same error with `fsevents` installation, it seems the error comes from `node-pre-gyp` 🤔

**Comment by wroughtec** [comment]
fsevents has an upgrade I hit that earlier too but upgrading that seems to resolve it

**Comment by Epimodev** [comment]
I just test again after remove the lock file and it works 🎉
I'll check if every thing works well with xxhashjs and publish an update

**Comment by wroughtec** [comment]
cool

**Comment by Epimodev** [comment]
I've just publish to npm version `1.1.2` which doesn't use anymore `xxhash`
Can you check if it works well for you ?

**Comment by wroughtec** [comment]
Yes seems to work thanks
