### ISSUE TITLE
Naming options

### ISSUE THREAD

**Issue by nikoloza** [Epimodev/parcel-plugin-svg-sprite#8]
It would be nice if we could set naming options to an output div inside `<use xlink:href="`

It could match the filenames with some prefix or suffix options too.

**Comment by Epimodev** [comment]
Hello,

I'm not sure to understand well what do you mean.
Do you want an option to customize symbol ids in the svg sprite?

**Comment by nikoloza** [comment]
Hi @Epimodev yes, exactly. 

In HTML if looks a bit long:
`<use xlink:href="#3962f97a2b91d187c055ec8f83354c26"></use>`

**Comment by Epimodev** [comment]
yes but you haven't to write the id in your code since everything is generated by parcel.

the only advantage I find by having this option is making debug easier.

is there other advantages for you by having this option ?

**Comment by nikoloza** [comment]
Yes, so I write a UIkit in Javascript which has usage in JS itself, but also in HTML where you get output like this:
```
<button class="ui square blue button">
  <svg><use xlink:href="#3962f97a2b91d187c055ec8f83354c26"></use></svg>
</button>
```

**Comment by Epimodev** [comment]
Ok, what do you think about the possibility to configure the symbol id in a file named `svgSprite.config.js` with a function named `getSymbolId` with `filePath` and `fileContent` params?
Do you think there are other parameters which can be useful to generate symbol id?
Have you got other idea about how I can make this configurable?

**Comment by nikoloza** [comment]
@Epimodev nope, that's perfect

**Comment by Epimodev** [comment]
ok thanks, I'll work on this during next days, I don't know when exactly.
I'll let you know

**Comment by nikoloza** [comment]
@Epimodev any updates?

**Comment by Epimodev** [comment]
Thanks for reminding me this issue.
I've got less time for open source last months.
But this week-end I've got nothing planned so I'll work on it tomorrow.

**Comment by Epimodev** [comment]
Hi @nikoloza 

I've just publish v1.4.0 with the possibility to set `getSymbolId` option from `svgSprite.config.js`.

Example of configuration:
```js
// svgSprite.config.js
const path = require('path');

module.exports = {
  getSymbolId: (filePath, fileContent, fileHash) => {
    return path.basename(filePath, '.svg');
  },
};
```

**Comment by nikoloza** [comment]
Works perfectly, thanks mate!
